// Mock data para desarrollo - Se usa cuando NODE_ENV=development y MOCK_DATA=true
export const mockUser = {
  id: "user_1",
  name: "Jefferson Mejia",
  email: "jefferson@example.com",
  emailVerified: true,
  image: null,
  createdAt: new Date(),
  updatedAt: new Date(),
}

export const mockMembers = [
  {
    id: "member_1",
    name: "Jefferson Mejia",
    email: "jefferson@example.com",
    role: "líder",
    avatar: "JM",
  },
  {
    id: "member_2",
    name: "Carlos García",
    email: "carlos@example.com",
    role: "colaborador",
    avatar: "CG",
  },
  {
    id: "member_3",
    name: "María López",
    email: "maria@example.com",
    role: "colaborador",
    avatar: "ML",
  },
  {
    id: "member_4",
    name: "Juan Rodriguez",
    email: "juan@example.com",
    role: "revisor",
    avatar: "JR",
  },
]

export const mockProjects = [
  {
    id: "proj_1",
    name: "Desarrollo Web Full Stack",
    description: "Crear una plataforma de e-commerce con React y Node.js",
    status: "activo",
    createdBy: "user_1",
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    members: mockMembers.slice(0, 3),
    taskCount: 3,
    completedTasks: 1,
  },
  {
    id: "proj_2",
    name: "Mobile App Flutter",
    description: "Aplicación móvil de fitness y ejercicios",
    status: "activo",
    createdBy: "user_1",
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    members: mockMembers.slice(0, 2),
    taskCount: 2,
    completedTasks: 1,
  },
  {
    id: "proj_3",
    name: "Machine Learning Predictivo",
    description: "Modelo de predicción de demanda de productos",
    status: "activo",
    createdBy: "user_1",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    members: mockMembers,
    taskCount: 0,
    completedTasks: 0,
  },
]

export const mockTasks = [
  {
    id: "task_1",
    projectId: "proj_1",
    title: "Diseñar base de datos",
    description: "Crear el esquema de la BD para la tienda",
    status: "completada",
    assignedTo: "user_1",
    dueDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    createdBy: "user_1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task_2",
    projectId: "proj_1",
    title: "Implementar autenticación",
    description: "Setup de login con JWT",
    status: "en_progreso",
    assignedTo: "user_1",
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    createdBy: "user_1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task_3",
    projectId: "proj_1",
    title: "Crear componentes UI",
    description: "Botones, inputs, modales",
    status: "pendiente",
    assignedTo: "user_1",
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    createdBy: "user_1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task_4",
    projectId: "proj_2",
    title: "Setup inicial de Flutter",
    description: "Configurar proyecto y dependencias",
    status: "completada",
    assignedTo: "user_1",
    dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    createdBy: "user_1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "task_5",
    projectId: "proj_2",
    title: "Pantalla de registro",
    description: "Crear interfaz de registro de usuarios",
    status: "en_progreso",
    assignedTo: "user_1",
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    createdBy: "user_1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockNotifications = [
  {
    id: "notif_1",
    userId: "user_1",
    type: "task_assigned",
    title: "Nueva tarea asignada",
    message: "Te asignaron: Implementar autenticación",
    read: false,
    link: "/dashboard/proyectos/proj_1/tareas",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "notif_2",
    userId: "user_1",
    type: "project_update",
    title: "Proyecto actualizado",
    message: "El proyecto 'Desarrollo Web Full Stack' fue actualizado",
    read: false,
    link: "/dashboard/proyectos/proj_1",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: "notif_3",
    userId: "user_1",
    type: "member_joined",
    title: "Nuevo miembro",
    message: "Carlos García se unió a 'Mobile App Flutter'",
    read: true,
    link: "/dashboard/proyectos/proj_2",
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
]
